### 

GET http://127.0.0.1:8000 HTTP/1.1


### 

POST http://127.0.0.1:8000/login/ HTTP/1.1
Content-Type: application/json

{
  "password": "secret",
  "username": "tino"
}


### 

POST http://127.0.0.1:8000/remove_bg/ HTTP/1.1
Content-Type: application/json

{
  "url": "https://i.pinimg.com/1200x/0a/28/01/0a280186d7f1d36212b85507e64e9871.jpg"
}
